<?php
return array(
	// Damage Statistics
	'damage_statistics' => 'Damage Statistics',
	'dps' => 'DPS',
	'dps-demon' => 'DPS vs Demons',
	'dps-elite' => 'DPS vs Elites',
	'aps-mh' => 'MH APS',
	'aps-oh' => 'OH APS',
	'critical-hit' => 'Critical Hit',
	'critical-hit-damage' => 'Critical Hit Damage',
	'attack-speed-incs' => '+% Attack Speed',
	// Base Statistics
	'base_statistics' => 'Base Statistics',
	'strength' => 'Strength',
	'dexterity' => 'Dexterity',
	'intelligence' => 'Intelligence',
	'vitality' => 'Vitality',
	'plus-magic-find' => 'Magic Find',
	'plus-gold-find' => 'Gold Find',
	'plus-movement' => 'Movement Speed',
	// Defensive Statistics
	'defensive_statistics' => 'Defensive Statistics',
	'armor' => 'Armor',
	'resist-all' => 'Resist All',
	'block-chance' => 'Block Chance',
	'dodge-chance' => 'Dodge Chance',
	'damage-reduction' => 'Damage Reduction (Armor)',
	'total-damage-reduction' => 'Damage Reduction (Total)',
	'thorns' => 'Thorns Damage',
	// Resistance Statistics
	'resistance_statistics' => 'Resistance Statistics',
	'resist-physical' => 'Physical Resistance',
	'resist-cold' => 'Cold Resistance',
	'resist-fire' => 'Fire Resistance',
	'resist-lightning' => 'Lightning Resistance',
	'resist-poison' => 'Poison Resistance',
	'resist-arcane' => 'Arcane/Holy Resistance',
	'cc-reduce' => 'Crowd Control Reduction',
	'percent-range-reduce' => 'Ranged Damage Reduction',
	'percent-melee-reduce' => 'Melee Damage Reduction',
	'percent-elite-reduce' => 'Elite Damage Reduction',
	// EHP Statistics
	'ehp_statistics' => 'EHP Statistics',
	'ehp-dodge' => 'EHP w/ Dodge',
	'ehp-block' => 'EHP w/ Block',
	'ehp-block-dodge' => 'EHP w/ Block + Dodge',
	'ehp-melee' => 'EHP vs Melee',
	'ehp-range' => 'EHP vs Ranged',
	'ehp-elite' => 'EHP vs Elite',
	'ehp-physical' => 'Physical EHP',
	'ehp-cold' => 'Cold EHP',
	'ehp-fire' => 'Fire EHP',
	'ehp-lightning' => 'Lightning EHP',
	'ehp-poison' => 'Poison EHP',
	'ehp-arcane' => 'Arcane/Holy EHP',
	// Health Statistics
	'health_statistics' => 'Health Statistics',
	'hp-ehp-ratio' => 'HP:EHP Ratio',
	'life' => 'Health',
	'life-steal' => 'Life Steal',
	'life-hit' => 'Life on Hit',
	'plus-life' => '+% Life',
	'life-regen' => 'Life/Sec Regen',
	'life-kill' => 'Life per Kill',
	'health-globes' => 'Globe/Potion Bonus',
	'plus-pickup-radius' => 'Pickup Radius',
);